// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxpmjqbxtlgkzemdyfwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cG1qcWJ4dGxna3plbWR5ZndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjI2MjUsImV4cCI6MjA2MTQzODYyNX0.di53Dy6RiAP5quYQ8OvpKn9LF6CAdTsOwKL0CKsiRYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);